apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "the-app.labels" . | nindent 4 }}
  name: {{ include "the-app.fullname" . }}-route
spec:
  host: kust-dev.apps-crc.testing
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ include "the-app.fullname" . }}-service
    weight: 100
  wildcardPolicy: None
